config/routes.rb
Ruby4kidswebsite::Application.routes.draw do
  devise_for :users

  resources :roles

  resources :web_pages

   root :to => 'home#index'
   resources :posts, :only => [:index, :show]

   

end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :title

  has_and_belongs_to_many :users

  def self.roles
    %w(admin).map {|name| Role.find_or_create_by_title(name)}
  end
end

app/models/syntax_highlighter.rb
require 'net/http'
require 'uri'

class SyntaxHighlighter
  PYGMENTS_URI = 'http://pygments.appspot.com/'
  attr_accessor :doc

  def initialize(html)
    self.doc = Nokogiri::HTML(html)
    doc.search("pre > code[class]").each do |code|
      request = Net::HTTP.post_form(URI.parse(PYGMENTS_URI), 
                  { 'lang' => code[:class],
                    'code' => code.text.rstrip })
      code.parent.replace request.body
    end
  end

  def to_s
    doc.search("//body").children.to_s
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :trackable 
  
  has_and_belongs_to_many :roles
  
  def role_symbols
    roles.map {|r| r.title.to_sym}
  end
  

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
  # attr_accessible :title, :body
end

app/models/web_page.rb
class WebPage < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged

  attr_accessible :content, :status, :title, :url

  before_save :write_html


  def write_html
    return if content.blank?
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML.new(hardwrap:true), 
                                       no_intra_emphasis:true, 
                                       autolink:true,
                                       fenced_code_blocks:true)

    syntax_highlighter = SyntaxHighlighter.new(markdown.render(content))
    self.html = Redcarpet::Render::SmartyPants.render(syntax_highlighter.to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def permission_denied
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'public'

  def index

  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    post = WebPage.last
    redirect_to post_path(post)
  end
  
  def show
    @post = WebPage.find(params[:id])
  end
  
  
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :authenticate_user!

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/web_pages_controller.rb
class WebPagesController < ApplicationController
  before_filter :authenticate_user!

  filter_access_to :all

  # GET /web_pages
  # GET /web_pages.json
  def index
    @web_pages = WebPage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @web_pages }
    end
  end

  # GET /web_pages/1
  # GET /web_pages/1.json
  def show
    @web_page = WebPage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @web_page }
    end
  end

  # GET /web_pages/new
  # GET /web_pages/new.json
  def new
    @web_page = WebPage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @web_page }
    end
  end

  # GET /web_pages/1/edit
  def edit
    @web_page = WebPage.find(params[:id])
  end

  # POST /web_pages
  # POST /web_pages.json
  def create
    @web_page = WebPage.new(params[:web_page])

    respond_to do |format|
      if @web_page.save
        format.html { redirect_to @web_page, notice: 'Web page was successfully created.' }
        format.json { render json: @web_page, status: :created, location: @web_page }
      else
        format.html { render action: "new" }
        format.json { render json: @web_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /web_pages/1
  # PUT /web_pages/1.json
  def update
    @web_page = WebPage.find(params[:id])

    respond_to do |format|
      if @web_page.update_attributes(params[:web_page])
        format.html { redirect_to @web_page, notice: 'Web page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @web_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /web_pages/1
  # DELETE /web_pages/1.json
  def destroy
    @web_page = WebPage.find(params[:id])
    @web_page.destroy

    respond_to do |format|
      format.html { redirect_to web_pages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/web_pages_helper.rb
module WebPagesHelper
end

app/views/home/index.html.erb
 <p>ruby4kids is a computer club consisting of a tech parent, a few volunteers and six kids. We get together Saturday afternoons to have fun while learning how to program.</p>
  <p>If you are a tech parent, thi is a great way to spend Saturday afternoons with your son or daughter, and their friends</p>
  <p>Become the cool parent while teaching them a valuable skill.</p>
  <p>We have covered ruby, Gosu, NXC for Mindstorms, iOS, and are now tackling Rails.</p>
  <p>Contact us to help you get started.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ruby4kidswebsite" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span12">
              <%= content_for?(:content) ? yield(:content) : yield %>
            </div>

        </div><!--/row-->
      </div><!--/content-->

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/posts.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ruby4kids" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <style type="text/css">

      /* Sticky footer styles
      -------------------------------------------------- */

      html,
      body {
        height: 100%;
        /* The html and body elements cannot have any padding or margin. */
      }

      /* Wrapper for page content to push down footer */
      #wrap {
        min-height: 100%;
        height: auto !important;
        height: 100%;
        /* Negative indent footer by it's height */
        margin: 0 auto -60px;
      }

      /* Set the fixed height of the footer here */
      #push,
      #footer {
        height: 60px;
      }
      #footer {
        background-color: #f5f5f5;
      }

      /* Lastly, apply responsive CSS fixes as necessary */
      @media (max-width: 767px) {
        #footer {
          margin-left: -20px;
          margin-right: -20px;
          padding-left: 20px;
          padding-right: 20px;
        }
      }



      /* Custom page CSS
      -------------------------------------------------- */
      /* Not required for template or sticky footer method. */

      .container {
        width: auto;
        max-width: 680px;
      }
      .container .credit {
        margin: 20px 0;
      }

    </style>
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>

  <body>


    <!-- Part 1: Wrap all page content here -->
    <div id="wrap">

      <!-- Begin page content -->
      <div class="container">
        <div class="page-header">
          <h1><%=yield :page_title%></h1>
        </div>
        	<%=yield %>
      </div>

      <div id="push"></div>
    </div>

    <div id="footer">
      <div class="container">
        <p class="muted credit">&copy; ruby4kids <%=Date.today.year%></p>
      </div>
    </div>



  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ruby4kidswebsite" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>


    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

	<div id="wrapper">
		<div id="header"></div>
		

  
		<div id="box1">
			  <div id="global-nav">
	            <ul>
	              <li><%= link_to "Ruby", "/path1"  %></li>
	              <li><%= link_to "Gosu", "/path2"  %></li>
	              <li><%= link_to "IOS", "/path3"  %></li>
	              <li><%= link_to "Lego Mindstorms", "/path3"  %></li>
	            </ul>
	          </div>
			
	    	<div id="box2">
			
				<div id="left-sidebar-nav">
			        <h3>Resources</h3>
			          <ul class="nav nav-list">
			            <li class="nav-header">Ruby</li>
			            <li><%= link_to "ruby.org", "/path1"  %></li>
			            <li><%= link_to "gosu", "/path2"  %></li>
						<li class="nav-header">IOS</li>
			            <li><%= link_to "Apple Developer Program", "/path1"  %></li>
			           	<li><%= link_to "Sample IOS Games", "/path2"  %></li>
			          </ul>
			     </div>
					<div id="content-wrapper">
	        			<div id="content">
							<%= yield %>
					     </div>
					</div>
					<div id="right-sidebar">
						Right sidebar content area
					</div>	
					<div style="clear:both;"></div>
				</div>
	        

	    </div>
          

     	<footer>
	      <p>&copy; ruby4kids 2012</p>
	      </footer>
     
</div> 

      

   

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/posts/index.html.erb
<%content_for :page_title do %>
	<%= @post.title%>
<% end %>

<%=raw @post.html%>

app/views/posts/show.html.erb
<%content_for :page_title do %>
	<%= @post.title%>
<% end %>

<%=raw @post.html%>

<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'ruby4kids'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.title %></td>
    <td><%= link_to 'Show', role %></td>
    <td><%= link_to 'Edit', edit_role_path(role) %></td>
    <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @role.title %>
</p>


<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/shared/denied.html.erb
<h1>
  Permission Denied
</h1>

app/views/web_pages/_form.html.erb
<%= form_for @web_page, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :status, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      web_pages_path, :class => 'btn' %>
    </div>
  <% end %>

app/views/web_pages/edit.html.erb
<%- model_class = WebPage -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/web_pages/index.html.erb
<%- model_class = WebPage -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:slug) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @web_pages.each do |web_page| %>
      <tr>
        <td><%= link_to web_page.id, web_page_path(web_page) %></td>
        <td><%= web_page.title %></td>
        <td><%= web_page.content %></td>
        <td><%= web_page.status %></td>
        <td><%= web_page.slug %></td>
        <td><%=l web_page.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_web_page_path(web_page), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      web_page_path(web_page),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_web_page_path,
            :class => 'btn btn-primary' %>

app/views/web_pages/new.html.erb
<%- model_class = WebPage -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/web_pages/show.html.erb
<%- model_class = WebPage -%>
<div class="page-header">
  <h1><%= @web_page.title %></h1>
</div>

<dl class="dl-horizontal">
  <pre><%= @web_page.content %></pre>
</dl>

<dl class="dl-horizontal">
  <%= raw @web_page.html %>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              web_pages_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_web_page_path(@web_page), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              web_page_path(@web_page),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>